### ISSUE TITLE
Why parse_lisa.py can not create total path?

### ISSUE THREAD

**Issue by Arlen0615** [glc12125/YOLO-for-LISA#2]
Hi glc12125,

Thanks very much for your sharing for LISA-TS,

I try your parse_lisa.py with "python parse_lisa.py allAnnotations.csv" and I got train.txt and test.txt, 
but it seems no aiua120214-0, aiua120214-1 etc.. in whole path, should I copy them out of each folder? 
do I miss something?

**Comment by glc12125** [comment]
Hey @Arlen0615 ,thanks for your question, I assume the issue was solved?

**Comment by Arlen0615** [comment]
Hi glc12125,

Actually not... I modify your parse_lisa.py to meet requirement of darknet train.txt and test.txt format.

I can start train.... but I don't know why I got "nan" after training a while, and the loss is not down either.

Like you said, I uses darknet19_448.conv.23 for training.

Maybe is src/detector.c, I not merge yours because your detector.c is too much different with AlexeyAB/darknet.
